
const vscode = require('vscode');

function activate(context) {

    let disposable1 = vscode.commands.registerCommand('extension.display', function () {

        var editor = vscode.window.activeTextEditor;
        if (!editor) {
            return; // No open text editor
        } else {
            var str = getRandomHook();
            editor.edit(editBuilder => {
                editBuilder.insert(editor.selection.active, str);
            });
        }
    });

    let disposable2 = vscode.commands.registerCommand('extension.displayWorded', function () {
        
        var editor = vscode.window.activeTextEditor;
        var window = vscode.window;
        if (!editor) {
            return; // No open text editor
        } else {
            window.showInputBox().then((numberOfWords) => {
                //console.log(numberOfWords);
                var str = getRandomVerse(parseInt(numberOfWords));
                editor.edit(editBuilder => {
                    editBuilder.insert(editor.selection.active, str);
                });
            });
        }
    });

    context.subscriptions.push(disposable1);
    context.subscriptions.push(disposable2);
}
exports.activate = activate;

function deactivate() {
}
exports.deactivate = deactivate;

function getRandomVerse(numberOfWords) {
    var str = full_verses[Math.floor(Math.random() * full_verses.length)];
    var words = str.split(" ");
    var ret_str = "";
    for (var i = 0; i < numberOfWords; i++) {
        ret_str += (words[i % words.length] + " ");
    }
    ret_str[ret_str.length-1]===" " ? ret_str = ret_str.slice(0, -1):true===true;
    ret_str += (ret_str[ret_str.length - 1] === "." || ret_str[ret_str.length - 1] === "?" || ret_str[ret_str.length - 1] === "!" || ret_str[ret_str.length - 1] === "," || ret_str[ret_str.length - 1] === ";") ? "" : ".";
    return ret_str;
}
function getRandomHook(){
    var ret_str = hooks[Math.floor(Math.random() * hooks.length)];
    ret_str += (ret_str[ret_str.length - 1] === "." || ret_str[ret_str.length - 1] === "?" || ret_str[ret_str.length - 1] === "!" || ret_str[ret_str.length - 1] === "," || ret_str[ret_str.length - 1] === ";") ? "" : ".";
    return ret_str;
}
var hooks = [
    "I'm Slim Shady, yes, I'm the real Shady. All you other Slim Shadys are just imitating. So won't the real Slim Shady please stand up. Please stand up, please stand up?. 'Cause I'm Slim Shady, yes, I'm the real Shady. All you other Slim Shadys are just imitating. So won't the real Slim Shady please stand up. Please stand up, please stand up?",

    "And I am whatever you say I am. If I wasn't, then why would I say I am?. In the paper, the news, every day I am. Radio won't even play my jam. ‘Cause I am whatever you say I am. If I wasn't, then why would I say I am?. In the paper, the news, every day I am. I don't know, it's just the way I am",

    "I'm not afraid to take a stand. Everybody, come take my hand. We'll walk this road together, through the storm. Whatever weather, cold or warm. Just lettin' you know that you're not alone. Holla if you feel like you've been down the same road",

    "If you could count the skeletons in my closet. Under my bed and up under my faucet. Then you would know I've completely lost it. Is he nuts? No, he's insane. If you could count the skeletons in my closet. Under my bed and up under my faucet. Then you would know I've completely lost it. Is he nuts? No, he's insane",

    "When you walked through the door. It was clear to me (Clear to me). You’re the one they adore. Who they came to see (Who they came to see). You’re a rock star (Baby). Everybody wants you (Everybody wants you). Player, who can really blame you? (Who can really blame you?). We’re the ones who made you",

    "We're gonna rock this house until we knock it down. So turn the volume loud. 'Cause it's mayhem 'til the A.M.. So, baby, make just like K-Fed. And let yourself go, let yourself go. Say \"Fuck it!\" before we kick the bucket. Life's too short to not go for broke. So everybody, everybody, go berserk, grab your vial, yeah",

    "I'm beginning to feel like a Rap God, Rap God. All my people from the front to the back nod, back nod. Now who thinks their arms are long enough to slap box, slap box?. Let me show you maintaining this shit ain't that hard, that hard. Everybody want the key and the secret. To rap immortality like I have got",

    "I'm beginning to feel like a Rap God, Rap God. All my people from the front to the back nod, back nod. The way I'm racing around the track, call me NASCAR, NASCAR. Dale Earnhardt of the trailer park, the White Trash God. Kneel before General Zod. This planet's Krypton – no, Asgard, Asgard",

    "Mom, I know I let you down. And though you say the days are happy. Why is the power off and I'm fucked up?. And, Mom, I know he's not around. But don't you place the blame on me. As you pour yourself another drink, yeah. I guess we are who we are. Headlights shining in the dark night, I drive on. Maybe we took this too far",

    "let's go back, follow the yellow brick road. As we go on another episode. Journey with me as I take you through this nifty little place. That I once used to call home sweet home. Come on, let's go back, follow the yellow brick road. As we go on another episode. Journey with me as I take you through this nifty little place. That I once used to call home sweet home",

    "I was gonna take the time to sit down and write you a little letter. But I thought a song would probably be a little better. Instead of a ,letter. That you'd probably just shred up--yeah. I stumbled on your picture yesterday and it made me stop and think of. How much of a waste it'd ,be for me to put some ink to, a stupid piece a. Paper, I'd rather let you see how. Much I fucking hate you in a freestyle",

    "The way she moves, she's like a belly-dancer. She's shaking that ass to the new Nelly jams. I think someone's at the door but I don't think I'mma answer. Police saying 'freeze!': do-doing, doing, doing. What do you mean, 'freeze'? Please, I'm a human being!. I have needs! I'm NOT done, not 'til I'm finished peeing",

    "Can't you see what you do to me, baby?. You make me crazy, you make me act like a maniac. I'm like a lunatic, you make me sick. You're truly the only one who can do this to me. You just make me get so crazy. I go schizo, I get so insane I just go schizophrenic. One minute I wanna slit your throat, the next I wanna sex",

    "I've created a monster, ‘cause nobody wants to. See Marshall no more, they want Shady, I'm chopped liver. Well, if you want Shady, this is what I'll give ya. A little bit of weed mixed with some hard liquor. Some vodka that'll jump start my heart quicker. Than a shock when I get shocked at the hospital",

    "I never meant to give you mushrooms, girl. I never meant to bring you to my world. Now you sitting in the corner crying. And now it's my fault, my fault. I never meant to give you mushrooms, girl. I never meant to bring you to my world. Now you sitting in the corner crying. And now it's my fault, my fault",

    "My tea's gone cold. I'm wondering why I got out of bed at all. The morning rain clouds up my window. And I can't see at all. And even if I could it'd all be gray. But your picture on my wall. It reminds me that it's not so bad, it's not so bad",

    "So bad, I’m so good that I’m so bad. Guarantee I’ll be the greatest thing you ever had. ‘Cause you ain't never met nobody like me. And you ain't gonna wanna fuck nobody else again. I'ma make you learn to appreciate me, differentiate me. From these phony, little fishy and sissy fake G’s. Skip over the \"huggy bear,\" and all the \"kissy face,\" please.",

    "I’m the American Dream. I’m the definiton of white trash ballin’. I’m right back on 'em. With a (chicka chicka chicka) I can’t call it. Same shit, different toilet. Oh, you got a nice ass, darling. Can’t wait to get you into my Benz, take you for a spin. What you mean we ain't fuckin’? You take me for a friend?. Let me tell you the whole story of Shady’s origin.",

    "Bagpipes from Baghdad. What's going through my mind. Half the time, when I rhyme, or blowing up like. Bagpipes from Baghdad. Somebody turn the vacancy sign on. 'Cause I'm gone, blowing on my. Bagpipes from Baghdad. I run the streets. And act like a madman holding a Glad.",

    "Feminist women love Eminem. \"Chicka, chicka, chicka, Slim Shady, I'm sick of him. Look at him, walkin' around, grabbin' his you-know-what. Flippin' the you-know-who,\" \"Yeah, but he's so cute though.\". Yeah, I probably got a couple of screws up in my head loose. But no worse than what's goin' on in your parents' bedrooms.",

    "Feminist women love Eminem. \"Chicka, chicka, chicka, Slim Shady, I'm sick of him. Look at him, walkin' around, grabbin' his you-know-what. Flippin' the you-know-who,\" \"Yeah, but he's so cute though.\". Yeah, I probably got a couple of screws up in my head loose. But no worse than what's goin' on in your parents' bedrooms.",

    "Feminist women love Eminem. \"Chicka, chicka, chicka, Slim Shady, I'm sick of him. Look at him, walkin' around, grabbin' his you-know-what. Flippin' the you-know-who,\" \"Yeah, but he's so cute though.\". Yeah, I probably got a couple of screws up in my head loose. But no worse than what's goin' on in your parents' bedrooms.",

    "Will the real Slim Shady please stand up?. I repeat, will the real Slim Shady please stand up?. We're gonna have a problem here. Y'all act like you never seen a white person before. Jaws all on the floor like Pam like Tommy just burst in the door. And started whoopin' her ass worse than before.",
];

var full_verses = [
    "Dear Stan, I meant to write you sooner, but I just been busy. You said your girlfriend's pregnant now, how far along is she? Look, I'm really flattered you would call your daughter that. And here's an autograph for your brother; I wrote it on a Starter cap. I'm sorry I didn't see you at the show, I musta missed you. Don't think I did that shit intentionally just to diss you. But what's this shit you said about you like to cut your wrists too? I say that shit just clownin' dawg, come on, how fucked up is you? You got some issues, Stan, I think you need some counselin' to help your ass from bouncin' Off the walls when you get down some. And what's this shit about us meant to be together? That type of shit'll make me not want us to meet each other. I really think you and your girlfriend need each other. Or maybe you just need to treat her better. I hope you get to read this letter, I just hope it reaches you in time. Before you hurt yourself, I think that you'll be doin' just fine if you relax a little. I'm glad I inspire you, but Stan why are you so mad? Try to understand that I do want you as a fan. I just don't want you to do some crazy shit. I seen this one shit on the news a couple weeks ago that made me sick. Some dude was drunk and drove his car over a bridge and had his girlfriend in the trunk and she was pregnant with his kid. and in the car they found a tape, but they didn't say who it was to. Come to think about it, his name was… it was you, damn.",
    
    "Hailie, I know you miss your mom, and I know you miss your dad when I'm gone. But I'm tryin' to give you the life that I never had. I can see you're sad, even when you smile, even when you laugh. I can see it in your eyes, deep inside you wanna cry. ‘Cause you're scared, I ain't there, daddy's with you in your prayers. No more crying, wipe them tears, daddy's here, no more nightmares. We gon' pull together through it, we gon' do it. Lainie, Uncle's crazy, ain't he? Yeah, but he loves you, girl, and you better know it. We're all we got in this world. When it spins, when it swirls, when it whirls, when it twirls. Two little beautiful girls, Looking puzzled, in a daze, I know it's confusing you. Daddy's always on the move, Momma's always on the news. I try to keep you sheltered from it, but somehow it seems the harder that I try to do that, the more it backfires on me. All the things growing up as Daddy that he had to see. Daddy don't want you to see, But you see just as much as he did. We did not plan it to be this way, your mother and me. But things have got so bad between us. I don't see us ever being together ever again. Like we used to be when we was teenagers, But then, of course, everything always happens for a reason. I guess it was never meant to be, But it's just something we have no control over, And that's what destiny is. But no more worries, rest your head and go to sleep. Maybe one day we'll wake up and this'll all just be a dream.",

    "Now hush, little baby, don't you cry. Everything's gonna be alright. Stiffen that upper lip up, little lady, I told ya. Daddy's here to hold ya through the night. I know Mommy's not here right now. And we don't know why. We fear how we feel inside. It may seem a little crazy, pretty baby. But I promise, Momma's gon' be alright. Heh, it's funny. I remember back one year when Daddy had no money. Mommy wrapped the Christmas presents up. And stuck 'em under the tree. And said some of 'em were from me. ‘Cause daddy couldn't buy 'em. I'll never forget that Christmas I sat up the whole night cryin'. ‘Cause Daddy felt like a bum – see, Daddy had a job. But his job was to keep the food on the table for you and Mom. And at the time, every house that we lived in. Either kept gettin' broken into and robbed or shot up on the block. And your mom was saving money for you in a jar. Tryin' to start a piggy bank for you so you could go to college. Almost had a thousand dollars. 'Til someone broke in and stole it. And I know it hurt so bad it broke your momma's heart. And it seemed like everything was just starting to fall apart.",

    "His palms are sweaty, knees weak, arms are heavy. There's vomit on his sweater already: Mom's spaghetti. He's nervous, but on the surface he looks calm and ready, To drop bombs, but he keeps on forgetting. What he wrote down, the whole crowd goes so loud. He opens his mouth, but the words won't come out. He's choking, how? Everybody's joking now, The clock's run out, time's up, over—blaow! Snap back to reality, oh, there goes gravity, oh, There goes Rabbit, he choked, he's so mad, but he won't, Give up that easy, no, he won't have it, he knows His whole back's to these ropes, it don't matter, he's dope. He knows that, but he's broke, he's so stagnant, he knows, When he goes back to this mobile home, that's when it's. Back to the lab again, yo! This whole rhapsody. Better go capture this moment and hope it don't pass him. You better lose yourself in the music, The moment, you own it, you better never let it go. You only get one shot, do not miss your chance to blow. This opportunity comes once in a lifetime, yo. You better lose yourself in the music. The moment, you own it, you better never let it go. You only get one shot, do not miss your chance to blow. This opportunity comes once in a lifetime, yo. You better… His soul's escaping through this hole that is gaping. This world is mine for the taking, make me king. As we move toward a New World Order. A normal life is boring; but superstardom's. Close to post-mortem, it only grows harder. Homie grows hotter, he blows, it's all over. These hoes is all on him, coast-to-coast shows. He's known as the Globetrotter, lonely roads. God only knows, he's grown farther from home, he's no father. He goes home and barely knows his own daughter.",

    "Snap back to reality, oh, there goes gravity, oh, There goes Rabbit, he choked, he's so mad, but he won't, Give up that easy, no, he won't have it, he knows His whole back's to these ropes, it don't matter, he's dope. He knows that, but he's broke, he's so stagnant, he knows, When he goes back to this mobile home, that's when it's. Back to the lab again, yo! This whole rhapsody. Better go capture this moment and hope it don't pass him. You better lose yourself in the music, The moment, you own it, you better never let it go. You only get one shot, do not miss your chance to blow. This opportunity comes once in a lifetime, yo. You better lose yourself in the music. The moment, you own it, you better never let it go. You only get one shot, do not miss your chance to blow. This opportunity comes once in a lifetime, yo. You better… His soul's escaping through this hole that is gaping. This world is mine for the taking, make me king. As we move toward a New World Order. A normal life is boring; but superstardom's. Close to post-mortem, it only grows harder. Homie grows hotter, he blows, it's all over. These hoes is all on him, coast-to-coast shows. He's known as the Globetrotter, lonely roads. God only knows, he's grown farther from home, he's no father. He goes home and barely knows his own daughter. His palms are sweaty, knees weak, arms are heavy. There's vomit on his sweater already: Mom's spaghetti. He's nervous, but on the surface he looks calm and ready, To drop bombs, but he keeps on forgetting. What he wrote down, the whole crowd goes so loud.",

    "May I have your attention, please?. Will the real Slim Shady please stand up?. I repeat, will the real Slim Shady please stand up?. We're gonna have a problem here. Y'all act like you never seen a white person before. Jaws all on the floor like Pam like Tommy just burst in the door. And started whoopin' her ass worse than before. They first were divorced, throwin' her over furniture {Aww!}. It's the return of the \"Ah, wait, no way, you're kidding. He didn't just say what I think he did, did he?\". And Dr. Dre said… nothing, you idiots!. Dr. Dre's dead, he's locked in my basement (ha ha!). Feminist women love Eminem. \"Chicka, chicka, chicka, Slim Shady, I'm sick of him. Look at him, walkin' around, grabbin' his you-know-what. Flippin' the you-know-who,\" \"Yeah, but he's so cute though.\". Yeah, I probably got a couple of screws up in my head loose. But no worse than what's goin' on in your parents' bedrooms. Sometimes I wanna get on TV and just let loose. But can't, but it's cool for Tom Green to hump a dead moose. \"My bum is on your lips, my bum is on your lips\". And if I'm lucky, you might just give it a little kiss. And that's the message that we deliver to little kids. And expect them not to know what a woman's clitoris is. Of course they're gonna know what intercourse is. By the time they hit fourth grade. They've got the Discovery Channel, don't they?. We ain't nothin' but mammals—well, some of us, cannibals. Who cut other people open like cantaloupes. But if we can hump dead animals and antelopes. Then there's no reason that a man and another man can't elope. But if you feel like I feel, I got the antidote. Women, wave your pantyhose, sing the chorus, and it goes..",

    "Feminist women love Eminem. \"Chicka, chicka, chicka, Slim Shady, I'm sick of him. Look at him, walkin' around, grabbin' his you-know-what. Flippin' the you-know-who,\" \"Yeah, but he's so cute though.\". Yeah, I probably got a couple of screws up in my head loose. But no worse than what's goin' on in your parents' bedrooms. Sometimes I wanna get on TV and just let loose. But can't, but it's cool for Tom Green to hump a dead moose. \"My bum is on your lips, my bum is on your lips\". And if I'm lucky, you might just give it a little kiss. And that's the message that we deliver to little kids. And expect them not to know what a woman's clitoris is. Of course they're gonna know what intercourse is. By the time they hit fourth grade. They've got the Discovery Channel, don't they?. We ain't nothin' but mammals—well, some of us, cannibals. Who cut other people open like cantaloupes. But if we can hump dead animals and antelopes. Then there's no reason that a man and another man can't elope. But if you feel like I feel, I got the antidote. Women, wave your pantyhose, sing the chorus, and it goes.. May I have your attention, please?. Will the real Slim Shady please stand up?. I repeat, will the real Slim Shady please stand up?. We're gonna have a problem here. Y'all act like you never seen a white person before. Jaws all on the floor like Pam like Tommy just burst in the door. And started whoopin' her ass worse than before. They first were divorced, throwin' her over furniture {Aww!}. It's the return of the \"Ah, wait, no way, you're kidding. He didn't just say what I think he did, did he?\". And Dr. Dre said… nothing, you idiots!. Dr. Dre's dead, he's locked in my basement (ha ha!).",

    "Locked in Mariah's wine cellar, all I had for lunch. Was bread, wine, more bread, wine and Captain Crunch. Red wine for breakfast and for brunch. And to soak it up, an in-between snack, crackers to munch. Mariah, what ever happened to us? Why did we have to break up?. All I asked for was a glass of punch. You see, I never really asked for much. I can't imagine what's going through your mind after such. A nasty break-up with that Latin hunk Luis Miguel. Nick Cannon better back the fuck up. I'm not playin', I want her back, ya punk. This is Hello Kitty bedspread, Satin Funk. Mixed with Egyptian with a little Rap and Punk. Zapp and Eric Clapton, Shaft, Frank Zappa, Crunk. And yeah, baby, I want another crack at ya. You can beat me with any spatula that you want. I mean, I really want you bad, you cunt. Nick, you had your fun, I've come to kick you in your sack of junk. Man, I could use a fresh batch of blood. So prepare your vernacular for Dracula acupuncture. Bagpipes from Baghdad. When will it ever cease?. For Pete sakes, he's crazy to say the least. Bagpipes from Baghdad. What's going through my mind. Half the time, when I rhyme, or blowing up like. Bagpipes from Baghdad. Somebody turn the vacancy sign on. 'Cause I'm gone, blowing on my. Bagpipes from Baghdad. I run the streets. And act like a madman holding a Glad. You can be a permanent fixture in my lyrical mixture. I'm the Miracle Whip trickster. My signature sound, when a tube of lipstick's around. I'm bound to put it on in an instant, wow. Man, what an ensemble. What an assortment of pharma–ceuticals. This beautiful pill dust in my palm, my. Cuticles get residue just from touchin' the bottle.",

    "Bagpipes from Baghdad. What's going through my mind. Half the time, when I rhyme, or blowing up like. Bagpipes from Baghdad. Somebody turn the vacancy sign on. 'Cause I'm gone, blowing on my. Bagpipes from Baghdad. I run the streets. And act like a madman holding a Glad. You can be a permanent fixture in my lyrical mixture. I'm the Miracle Whip trickster. My signature sound, when a tube of lipstick's around. I'm bound to put it on in an instant, wow. Man, what an ensemble. What an assortment of pharma–ceuticals. This beautiful pill dust in my palm, my. Cuticles get residue just from touchin' the bottle. Locked in Mariah's wine cellar, all I had for lunch. Was bread, wine, more bread, wine and Captain Crunch. Red wine for breakfast and for brunch. And to soak it up, an in-between snack, crackers to munch. Mariah, what ever happened to us? Why did we have to break up?. All I asked for was a glass of punch. You see, I never really asked for much. I can't imagine what's going through your mind after such. A nasty break-up with that Latin hunk Luis Miguel. Nick Cannon better back the fuck up. I'm not playin', I want her back, ya punk. This is Hello Kitty bedspread, Satin Funk. Mixed with Egyptian with a little Rap and Punk. Zapp and Eric Clapton, Shaft, Frank Zappa, Crunk. And yeah, baby, I want another crack at ya. You can beat me with any spatula that you want. I mean, I really want you bad, you cunt. Nick, you had your fun, I've come to kick you in your sack of junk. Man, I could use a fresh batch of blood. So prepare your vernacular for Dracula acupuncture. Bagpipes from Baghdad. When will it ever cease?. For Pete sakes, he's crazy to say the least.",

    "You can be a permanent fixture in my lyrical mixture. I'm the Miracle Whip trickster. My signature sound, when a tube of lipstick's around. I'm bound to put it on in an instant, wow. Man, what an ensemble. What an assortment of pharma–ceuticals. This beautiful pill dust in my palm, my. Cuticles get residue just from touchin' the bottle. Locked in Mariah's wine cellar, all I had for lunch. Was bread, wine, more bread, wine and Captain Crunch. Red wine for breakfast and for brunch. And to soak it up, an in-between snack, crackers to munch. Mariah, what ever happened to us? Why did we have to break up?. All I asked for was a glass of punch. You see, I never really asked for much. I can't imagine what's going through your mind after such. A nasty break-up with that Latin hunk Luis Miguel. Nick Cannon better back the fuck up. I'm not playin', I want her back, ya punk. This is Hello Kitty bedspread, Satin Funk. Mixed with Egyptian with a little Rap and Punk. Zapp and Eric Clapton, Shaft, Frank Zappa, Crunk. And yeah, baby, I want another crack at ya. You can beat me with any spatula that you want. I mean, I really want you bad, you cunt. Nick, you had your fun, I've come to kick you in your sack of junk. Man, I could use a fresh batch of blood. So prepare your vernacular for Dracula acupuncture. Bagpipes from Baghdad. When will it ever cease?. For Pete sakes, he's crazy to say the least.",

    "My words are like a dagger with a jagged edge. That'll stab you in the head, whether you're a fag or lez. Or a homosex, hermaph or a trans-a-vest. Pants or dress, hate fags? The answer's yes. Homophobic? Nah, you're just heterophobic. Staring at my jeans, watching my genitals bulgin'. That's my motherfuckin' balls, you'd better let go of 'em. They belong in my scrotum, you'll never get hold of 'em!. \"Hey, it's me, Versace! Whoops, somebody shot me!. And I was just checkin' the mail. Get it? Checkin' the male?\". How many records you expecting to sell. After your second LP sends you directly to jail?. Come on, relax, guy! I like gay men. Right, Ken? Give me an amen! (A-men!). \"Please Lord, this boy needs Jesus. Heal this child, help us destroy these demons. Oh, and please send me a brand new car. And a prostitute while my wife's sick in the hospital\". Preacher, preacher! Fifth grade teacher!. You can't reach me, my mom can't neither. You can't teach me a goddamn thing ‘cause. I watch TV and Comcast cable. And you ain't able to stop these thoughts. You can't stop me from toppin' these charts. And you can't stop me from droppin' each March. With a brand new CD for these fuckin' retards. And to think, it's just lil old me. Mr. Don't-Give-a-Fuck still won't leave. I'm a criminal!. ‘Cause every time I write a rhyme. These people think it's a crime. To tell 'em what's on my mind. I guess I'm a criminal!. I don't gotta say a word. I just flip 'em the bird and keep goin'. I don't take shit from no one. The mother did drugs, hard liquor, cigarettes and speed. The baby came out, disfigured ligaments, indeed. It was a seed who would grow up just as crazy as she.",

    "They call me Superman. Leap tall hoes in a single bound. I'm single now: got no ring on this finger now. I'd never let another chick bring me down. In a relationship; save it, bitch!. Babysit? You make me sick. Superman ain't savin' shit. Girl, you can jump on Shady's dick. Straight from the hip, cut to the chase. I tell a motherfuckin' slut to her face. Play no games, say no names. Ever since I broke up with what's-her-face. I'm a different man, kiss my ass. Kiss my lips? Bitch, why ask?. Kiss my dick, get my cash?. I'd rather have you whip my ass. Don't put out, I'll put you out. Won't get out, I'll push you out. Puss blew out, poppin' shit. Wouldn't piss on fire to put you out. Am I too nice? Buy you ice?. Bitch, if you died, wouldn't buy you life. What, you tryin' to be my new wife?. What, you Mariah? Fly through twice. But I do know one thing though. Bitches, they come, they go. Saturday through Sunday, Monday. Monday through Sunday, yo. Maybe I'll love you one day. Maybe we'll someday grow. 'Til then just sit your drunk ass on that fuckin' runway, ho. Don't get me wrong, I love these hoes. It's no secret, everybody knows. Yeah, we fucked: bitch, so what?. That's about as far as your buddy goes. We'll be friends, I'll call you again. I'll chase you around every bar you attend. Never know what kinda car I be in. We'll see how much you be partyin' then. You don't want that, neither do I. I don't wanna flip when I see you with guys. Too much pride, between you and I. Not a jealous man, but females lie. But I guess that's just what sluts do. How could it ever be just us two?. I'd never love you enough to trust you. We just met and I just fucked you.",

    "I know you want me, baby, I think I want you too. (I think I love you, baby) I think I love you too. I'm here to save you, girl, come be in Shady's world. I wanna grow together, let's let our love unfurl. You know you want me, baby, you know I want you too. They call me Superman, I'm here to rescue you. I wanna save you, girl, come be in Shady's world. (Ooh boy, you drive me crazy) Bitch, you make me hurl. First thing you say: (I'm not fazed. I hang around big stars all day. I don't see what the big deal is anyway. You're just plain old Marshall to me). Ooh yeah, girl, run that game. (Hailie Jade, I love that name. Love that tattoo, what's that say?. \"Rot In Pieces,\" uh, that's great). First off, you don't know Marshall. At all, so don't grow partial. That's ammo for my arsenal. I'll slap you off that bar stool. There goes another lawsuit. Leave handprints all across you. Good Lordy, whoadie. You must be gone off that water bottle. You want what you can't have. Ooh girl, that's too damn bad. Don't touch what you can't grab. End up with two backhands. Put anthrax on a Tampax. And slap you 'til you can't stand. Girl, you just blew your chance. Don't mean to ruin your plans. But I do know one thing though. Bitches, they come, they go. Saturday through Sunday, Monday. Monday through Sunday, yo. Maybe I'll love you one day. Maybe we'll someday grow. 'Til then just sit your drunk ass on that fuckin' runway, ho. ‘Cause I can't be your Superman. Can't be your Superman. Can't be your Superman. Can't be your Superman.",

    "But I do know one thing though. Bitches, they come, they go. Saturday through Sunday, Monday. Monday through Sunday, yo. Maybe I'll love you one day. Maybe we'll someday grow. 'Til then just sit your drunk ass on that fuckin' runway, ho. ‘Cause I can't be your Superman. Can't be your Superman. Can't be your Superman. Can't be your Superman. I know you want me, baby, I think I want you too. (I think I love you, baby) I think I love you too. I'm here to save you, girl, come be in Shady's world. I wanna grow together, let's let our love unfurl. You know you want me, baby, you know I want you too. They call me Superman, I'm here to rescue you. I wanna save you, girl, come be in Shady's world. (Ooh boy, you drive me crazy) Bitch, you make me hurl. First thing you say: (I'm not fazed. I hang around big stars all day. I don't see what the big deal is anyway. You're just plain old Marshall to me). Ooh yeah, girl, run that game. (Hailie Jade, I love that name. Love that tattoo, what's that say?. \"Rot In Pieces,\" uh, that's great).",

    "First off, you don't know Marshall. At all, so don't grow partial. That's ammo for my arsenal. I'll slap you off that bar stool. There goes another lawsuit. Leave handprints all across you. Good Lordy, whoadie. You must be gone off that water bottle. You want what you can't have. Ooh girl, that's too damn bad. Don't touch what you can't grab. End up with two backhands. Put anthrax on a Tampax. And slap you 'til you can't stand. Girl, you just blew your chance. Don't mean to ruin your plans. But I do know one thing though. Bitches, they come, they go. Saturday through Sunday, Monday. Monday through Sunday, yo. Maybe I'll love you one day. Maybe we'll someday grow. 'Til then just sit your drunk ass on that fuckin' runway, ho. ‘Cause I can't be your Superman. Can't be your Superman. Can't be your Superman. Can't be your Superman.",

    "I'm a different man, kiss my ass. Kiss my lips? Bitch, why ask?. Kiss my dick, get my cash?. I'd rather have you whip my ass. Don't put out, I'll put you out. Won't get out, I'll push you out. Puss blew out, poppin' shit. Wouldn't piss on fire to put you out. Am I too nice? Buy you ice?. Bitch, if you died, wouldn't buy you life. What, you tryin' to be my new wife?. What, you Mariah? Fly through twice. But I do know one thing though. Bitches, they come, they go. Saturday through Sunday, Monday. Monday through Sunday, yo. Maybe I'll love you one day. Maybe we'll someday grow. 'Til then just sit your drunk ass on that fuckin' runway, ho. Don't get me wrong, I love these hoes. It's no secret, everybody knows. Yeah, we fucked: bitch, so what?. That's about as far as your buddy goes. We'll be friends, I'll call you again. I'll chase you around every bar you attend. Never know what kinda car I be in. We'll see how much you be partyin' then. You don't want that, neither do I. I don't wanna flip when I see you with guys. Too much pride, between you and I. Not a jealous man, but females lie. But I guess that's just what sluts do. How could it ever be just us two?. I'd never love you enough to trust you. We just met and I just fucked you.", 

    "I’m the American Dream. I’m the definiton of white trash ballin’. I’m right back on 'em. With a (chicka chicka chicka) I can’t call it. Same shit, different toilet. Oh, you got a nice ass, darling. Can’t wait to get you into my Benz, take you for a spin. What you mean we ain't fuckin’? You take me for a friend?. Let me tell you the whole story of Shady’s origin. You’ll be sorry if you slam my Mercedes door again. Now, it all started with my father. I must’ve got my pimpin' genes from him. The way he left my momma. I’m a rolling stone, just like him, word to Johnny Drama. Keep my entourage with me, baby, I’ll make a promise. There ain't nobody as bomb as me. I’m as calm as the breeze. I’m the bee’s knees, his legs, and his arms. I'm a superstar, girl, I’m ready for you, mama. Why you think the only thing I got on is my pajamas?. So bad, I’m so good that I’m so bad. Guarantee I’ll be the greatest thing you ever had. ‘Cause you ain't never met nobody like me. And you ain't gonna wanna fuck nobody else again. I'ma make you learn to appreciate me, differentiate me. From these phony, little fishy and sissy fake G’s. Skip over the \"huggy bear,\" and all the \"kissy face,\" please. Initiate phase three, missy, now service me. Take another shot of Jäger, shakin' so nervously. Take your time, baby, oh, you’re the bomb, baby. Oh, you’re doing that even better than your mom, lady. I told you why I’m Shady, you didn't listen now, did ya?. Relax woman, you know that I’m only kiddin' with ya. Got a twisted sense of humor, its warped, but I didn't hit ya. I think you’re finally starting to get the picture. I’m just…", 

    "So bad, I’m so good that I’m so bad. Guarantee I’ll be the greatest thing you ever had. ‘Cause you ain't never met nobody like me. And you ain't gonna wanna fuck nobody else again. I'ma make you learn to appreciate me, differentiate me. From these phony, little fishy and sissy fake G’s. Skip over the \"huggy bear,\" and all the \"kissy face,\" please. Initiate phase three, missy, now service me. Take another shot of Jäger, shakin' so nervously. Take your time, baby, oh, you’re the bomb, baby. Oh, you’re doing that even better than your mom, lady. I told you why I’m Shady, you didn't listen now, did ya?. Relax woman, you know that I’m only kiddin' with ya. Got a twisted sense of humor, its warped, but I didn't hit ya. I think you’re finally starting to get the picture. I’m just…"
];
